// Auto-generated by scrape_jobs.js — do not edit manually.
// City: Krakow  Scraped: 2026-04-07T15:12:27.768Z
var cityJobs = [
  {
    "title": "Specjalistka / Specjalista ds. programów edukacyjnych w wydawnictwie gier planszowych",
    "salary": "5 300–5 700 zł / mies. (zal. od umowy)",
    "company": "WYDAWNICTWO IUVI sp. z o.o. sp.j.",
    "location": "Kraków, Bieżanów-Prokocim",
    "url": "https://www.pracuj.pl/praca/specjalistka-specjalista-ds-programow-edukacyjnych-w-wydawnictwie-gier-planszowy-krakow-pollanki-12c,oferta,1004754979"
  },
  {
    "title": "Doradca Klienta Indywidualnego",
    "salary": "8 750–20 000 zł / mies. (zal. od umowy)",
    "company": "Tutlo Sp. z o.o.",
    "location": "Kraków, Stare Miasto",
    "url": "https://www.pracuj.pl/praca/doradca-klienta-indywidualnego-krakow-aleja-29-listopada-20,oferta,1004742338"
  },
  {
    "title": "Franczyzobiorca w branży e-commerce i logistyki",
    "salary": "20 000–35 000 zł netto (+ VAT) / mies.",
    "company": "Mail Boxes Etc.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/franczyzobiorca-w-branzy-e-commerce-i-logistyki-krakow,oferta,1004706485"
  },
  {
    "title": "Data Engineer",
    "salary": "22 000–26 000 zł netto (+ VAT) / mies.",
    "company": "Mindbox Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/data-engineer-krakow,oferta,1004700413"
  },
  {
    "title": "Fullstack Developer",
    "salary": "22 000–26 000 zł netto (+ VAT) / mies.",
    "company": "Mindbox Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/fullstack-developer-krakow,oferta,1004700385"
  },
  {
    "title": "Przedstawiciel handlowy / Przedstawicielka handlowa",
    "salary": "9 000–15 000 zł brutto / mies.",
    "company": "\"JBB\" BAŁDYGA Józef Bałdyga",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/przedstawiciel-handlowy-przedstawicielka-handlowa-krakow,oferta,1004706620"
  },
  {
    "title": "Regionalny Przedstawiciel Handlowy / Regionalna Przedstawicielka Handlowa (Fizjoterapeuta) – sprzęt fizjo / rehab",
    "salary": "5 000–20 000 zł / mies. (zal. od umowy)",
    "company": "BardoMed Sp. z o. o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/regionalny-przedstawiciel-handlowy-regionalna-przedstawicielka-handlowa-fizjoter-krakow,oferta,1004739875"
  },
  {
    "title": "National Account Manager (NAM)",
    "salary": "8 500–10 000 zł / mies. (zal. od umowy)",
    "company": "WeNet Group SA",
    "location": "Kraków, Podgórze",
    "url": "https://www.pracuj.pl/praca/national-account-manager-nam-krakow-wadowicka-6,oferta,1004725171"
  },
  {
    "title": "Konsultant / Konsultantka Sprzedaży Bezpośredniej",
    "salary": "5 000–6 500 zł brutto / mies.",
    "company": "WeNet Group SA",
    "location": "Kraków, Podgórze",
    "url": "https://www.pracuj.pl/praca/konsultant-konsultantka-sprzedazy-bezposredniej-krakow-wadowicka-6,oferta,1004725155"
  },
  {
    "title": "Starszy Specjalista / Starsza Specjalistka ds. Sprzedaży Usług Marketingowych",
    "salary": "5 500–6 500 zł brutto / mies.",
    "company": "WeNet sp. z o.o.",
    "location": "Kraków, Podgórze",
    "url": "https://www.pracuj.pl/praca/starszy-specjalista-starsza-specjalistka-ds-sprzedazy-uslug-marketingowych-krakow-wadowicka-6,oferta,1004725140"
  },
  {
    "title": "Młodszy Specjalista / Młodsza Specjalistka ds. Sprzedaży Usług Marketingowych",
    "salary": "4 900–5 400 zł brutto / mies.",
    "company": "WeNet sp. z o.o.",
    "location": "Kraków, Podgórze",
    "url": "https://www.pracuj.pl/praca/mlodszy-specjalista-mlodsza-specjalistka-ds-sprzedazy-uslug-marketingowych-krakow-wadowicka-6,oferta,1004725147"
  },
  {
    "title": "Ekspert / Ekspertka ds. Sprzedaży SEO & ADS",
    "salary": "6 000–8 000 zł / mies. (zal. od umowy)",
    "company": "WeNet sp. z o.o.",
    "location": "Kraków, Podgórze",
    "url": "https://www.pracuj.pl/praca/ekspert-ekspertka-ds-sprzedazy-seo-ads-krakow-wadowicka-6,oferta,1004725136"
  },
  {
    "title": "Opiekun / Opiekunka Klienta - mKiosk mBanku",
    "salary": "5 750–10 150 zł brutto / mies.",
    "company": "mFinanse S.A.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/opiekun-opiekunka-klienta-mkiosk-mbanku-krakow,oferta,1004736601"
  },
  {
    "title": "Lektor / Lektorka - Nauczyciel / Nauczycielka języka angielskiego (ONLINE)",
    "salary": "5 400–7 000 zł / mies. (zal. od umowy)",
    "company": "Tutlo Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/lektor-lektorka-nauczyciel-nauczycielka-jezyka-angielskiego-online-krakow,oferta,1004748768"
  },
  {
    "title": "Magazynier / Magazynierka, Operator / Operatorka wózka widłowego (k/m)",
    "salary": "5 100–6 100 zł brutto / mies.",
    "company": "U Jędrusia",
    "location": "Morawica (pow. krakowski)",
    "url": "https://www.pracuj.pl/praca/magazynier-magazynierka-operator-operatorka-wozka-widlowego-k-m-morawica-pow-krakowski-306,oferta,1004751391"
  },
  {
    "title": "Telefoniczna obsługa klienta Orange (bez doświadczenia)",
    "salary": "32,50–40 zł brutto / godz.",
    "company": "Armatis Polska Sp. Z o. o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/telefoniczna-obsluga-klienta-orange-bez-doswiadczenia-krakow,oferta,1004739701"
  },
  {
    "title": "Cloud FinOps Programme Manager – Technology Infrastructure Optimization",
    "salary": "23 100–29 400 zł / mies. (zal. od umowy)",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/cloud-finops-programme-manager-technology-infrastructure-optimization-krakow,oferta,1004742307"
  },
  {
    "title": "Mid-Level Business Data Analyst",
    "salary": "23 100–25 200 zł / mies. (zal. od umowy)",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/mid-level-business-data-analyst-krakow,oferta,1004724859"
  },
  {
    "title": "Pracownik / Pracowniczka Restauracji KFC Widoma S7 MOP West",
    "salary": "31–32 zł brutto / godz.",
    "company": "AmRest Sp. z o.o. - KFC",
    "location": "Poskwitów (pow. krakowski)",
    "url": "https://www.pracuj.pl/praca/pracownik-pracowniczka-restauracji-kfc-widoma-s7-mop-west-poskwitow-pow-krakowski,oferta,1004754921"
  },
  {
    "title": "Business Analyst – Cybersecurity Endpoint Protection",
    "salary": "23 100–27 300 zł / mies. (zal. od umowy)",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/business-analyst-cybersecurity-endpoint-protection-krakow,oferta,1004724858"
  },
  {
    "title": "Senior Network Visibility and Cybersecurity Requirements Analyst",
    "salary": "25 200–29 400 zł / mies. (zal. od umowy)",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/senior-network-visibility-and-cybersecurity-requirements-analyst-krakow,oferta,1004724851"
  },
  {
    "title": "Fullstack Engineer",
    "salary": "24 000–29 600 zł netto (+ VAT) / mies.",
    "company": "Mindbox Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/fullstack-engineer-krakow,oferta,1004742287"
  },
  {
    "title": "Senior Fullstack Engineer – .NET and React Analytics Platform",
    "salary": "24 150–30 450 zł / mies. (zal. od umowy)",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/senior-fullstack-engineer-net-and-react-analytics-platform-krakow,oferta,1004742285"
  },
  {
    "title": "Pracownik / Pracowniczka Restauracji KFC Opolska",
    "salary": "31–32 zł brutto / godz.",
    "company": "AmRest Sp. z o.o. - KFC",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/pracownik-pracowniczka-restauracji-kfc-opolska-krakow,oferta,1004754891"
  },
  {
    "title": "Senior Java React Tech Lead – Payments Platform",
    "salary": "25 200–29 400 zł / mies. (zal. od umowy)",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/senior-java-react-tech-lead-payments-platform-krakow,oferta,1004742283"
  },
  {
    "title": "Senior Threat and Controls Assessment Analyst – Cybersecurity",
    "salary": "18 900–25 200 zł / mies. (zal. od umowy)",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/senior-threat-and-controls-assessment-analyst-cybersecurity-krakow,oferta,1004742279"
  },
  {
    "title": "Specjalista / Specjalistka ds. obsługi klienta",
    "salary": "5 000–8 000 zł / mies. (zal. od umowy)",
    "company": "MATURALNI sp. z o.o.",
    "location": "Kraków, Łagiewniki-Borek Fałęcki",
    "url": "https://www.pracuj.pl/praca/specjalista-specjalistka-ds-obslugi-klienta-krakow-narcyzy-zmichowskiej-18,oferta,1004715809"
  },
  {
    "title": "Mid-Level Java & React Microservices Engineer – Payments Platform",
    "salary": "23 100–27 300 zł / mies. (zal. od umowy)",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/mid-level-java-react-microservices-engineer-payments-platform-krakow,oferta,1004742274"
  },
  {
    "title": "DevOps & Python Backend Engineer",
    "salary": "26 000–39 000 zł netto (+ VAT) / godz.",
    "company": "ITEAMLY SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/devops-python-backend-engineer-krakow,oferta,1004754879"
  },
  {
    "title": "Key Account Manager (izolacje techniczne)",
    "salary": "15 000 zł brutto / mies.",
    "company": "SALES HR",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/key-account-manager-izolacje-techniczne-krakow,oferta,1004754875"
  },
  {
    "title": "Full-Stack Developer (Java, Angular)",
    "salary": "21 000–24 000 zł brutto / mies.",
    "company": "Motife Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/full-stack-developer-java-angular-krakow,oferta,1004724824"
  },
  {
    "title": "Pracownik / Pracowniczka Restauracji KFC Futura",
    "salary": "31–32 zł brutto / godz.",
    "company": "AmRest Sp. z o.o. - KFC",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/pracownik-pracowniczka-restauracji-kfc-futura-krakow,oferta,1004754845"
  },
  {
    "title": "Pracownik / Pracowniczka Restauracji KFC Modlnica",
    "salary": "31–32 zł brutto / godz.",
    "company": "AmRest Sp. z o.o. - KFC",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/pracownik-pracowniczka-restauracji-kfc-modlnica-krakow,oferta,1004754835"
  },
  {
    "title": "Pracownik / Pracowniczka Restauracji KFC Węzeł Mirowski",
    "salary": "31–32 zł brutto / godz.",
    "company": "AmRest Sp. z o.o. - KFC",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/pracownik-pracowniczka-restauracji-kfc-wezel-mirowski-krakow,oferta,1004754834"
  },
  {
    "title": "Head of Cloud and Container Device Protection",
    "salary": "23 300–34 500 zł brutto / mies.",
    "company": "HSBC Service Delivery (Polska) Sp. z o.o.",
    "location": "Kraków, Dębniki",
    "url": "https://www.pracuj.pl/praca/head-of-cloud-and-container-device-protection-krakow-kapelanka-42a,oferta,1004754792"
  },
  {
    "title": "Młodszy Przedstawiciel Handlowy - Młodszy Inżynier Sprzedaży - Junior Key Account Manager with English (fresh graduates)",
    "salary": "10 000–12 000 zł brutto / mies.",
    "company": "Recruit Europe Sp.zo.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/mlodszy-przedstawiciel-handlowy-mlodszy-inzynier-sprzedazy-junior-key-account-ma-krakow,oferta,1004754789"
  },
  {
    "title": "Asystent / Asystentka - Recepcjonista / Recepcjonistka",
    "salary": "4 900–5 500 zł brutto / mies.",
    "company": "AUTO KRAK SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",
    "location": "Kraków, Prądnik Biały",
    "url": "https://www.pracuj.pl/praca/asystent-asystentka-recepcjonista-recepcjonistka-krakow-walerego-eljasza-radzikowskiego-160,oferta,1004727805"
  },
  {
    "title": "Specjalista ds. Certyfikacji / Specjalistka ds. Certyfikacji / Starszy Specjalista ds. Certyfikacji / Starsza Specjalistka ds. Certyfikacji",
    "salary": "6 000–8 500 zł brutto / mies.",
    "company": "Instytut Nafty i Gazu - Państwowy Instytut Badawczy",
    "location": "Kraków, Grzegórzki",
    "url": "https://www.pracuj.pl/praca/specjalista-ds-certyfikacji-specjalistka-ds-certyfikacji-starszy-specjalista-ds-krakow-lubicz-25a,oferta,1004754664"
  },
  {
    "title": "Dyrektor / Dyrektorka Sprzedaży",
    "salary": "20 000–25 000 zł netto (+ VAT) / mies.",
    "company": "HireWise Szymon Negacz sp.k.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/dyrektor-dyrektorka-sprzedazy-krakow,oferta,1004739552"
  },
  {
    "title": "Sprzedawca – lada tradycyjna (m/k)",
    "salary": "2 655–2 905 zł brutto / mies.",
    "company": "Biedronka (Jeronimo Martins Polska S.A.)",
    "location": "Wiśniowa (pow. myślenicki)",
    "url": "https://www.pracuj.pl/praca/sprzedawca-lada-tradycyjna-m-k-wisniowa-pow-myslenicki-749,oferta,1004742476"
  },
  {
    "title": "Automation Intern",
    "salary": "31,40–35 zł brutto / godz.",
    "company": "GGS IT Consulting",
    "location": "Kraków, Grzegórzki",
    "url": "https://www.pracuj.pl/praca/automation-intern-krakow-cystersow-13a,oferta,1004754602"
  },
  {
    "title": "Support Specialist with SQL",
    "salary": "8 000–12 000 zł / mies. (zal. od umowy)",
    "company": "GGS IT Consulting",
    "location": "Kraków, Grzegórzki",
    "url": "https://www.pracuj.pl/praca/support-specialist-with-sql-krakow-cystersow-13,oferta,1004754600"
  },
  {
    "title": "Automation Support Specialist",
    "salary": "8 000–12 000 zł / mies. (zal. od umowy)",
    "company": "GGS IT Consulting",
    "location": "Kraków, Grzegórzki",
    "url": "https://www.pracuj.pl/praca/automation-support-specialist-krakow-cystersow-13a,oferta,1004754596"
  },
  {
    "title": "Doradca Techniczno Handlowy (k/m)",
    "salary": "6 000–14 000 zł / mies. (zal. od umowy)",
    "company": "Sabaj System Sp. z o.o.",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/doradca-techniczno-handlowy-k-m-krakow,oferta,1004739495"
  },
  {
    "title": "Manager Financial Crime Analysis",
    "salary": "16 565–24 840 zł brutto / mies.",
    "company": "HSBC Service Delivery (Polska) Sp. z o.o.",
    "location": "Kraków, Dębniki",
    "url": "https://www.pracuj.pl/praca/manager-financial-crime-analysis-krakow-kapelanka-42a,oferta,1004715559"
  },
  {
    "title": "Kelner / Kelnerka",
    "salary": "31,40–35 zł brutto / godz.",
    "company": "RESTAURACJA GRANDA",
    "location": "Myślenice",
    "url": "https://www.pracuj.pl/praca/kelner-kelnerka-myslenice-kasprowicza-13a,oferta,1004724653"
  },
  {
    "title": "Administrator / Administratorka sieci komputerowej",
    "salary": "10 000–16 000 zł brutto / mies.",
    "company": "Akademia Górniczo-Hutnicza im. Stanisława Staszica w Krakowie",
    "location": "Kraków, Krowodrza",
    "url": "https://www.pracuj.pl/praca/administrator-administratorka-sieci-komputerowej-krakow-kawiory-21,oferta,1004724627"
  },
  {
    "title": "DevOps",
    "salary": "12 000–18 000 zł brutto / mies.",
    "company": "Akademia Górniczo-Hutnicza im. Stanisława Staszica w Krakowie",
    "location": "Kraków, Krowodrza",
    "url": "https://www.pracuj.pl/praca/devops-krakow-kawiory-21,oferta,1004724609"
  },
  {
    "title": "Administrator / Administratorka IT",
    "salary": "9 000–15 000 zł brutto / mies.",
    "company": "Akademia Górniczo-Hutnicza im. Stanisława Staszica w Krakowie",
    "location": "Kraków, Krowodrza",
    "url": "https://www.pracuj.pl/praca/administrator-administratorka-it-krakow-kawiory-21,oferta,1004724607"
  },
  {
    "title": "Inżynier wsparcia technicznego – Zuken E3.series (m/k)",
    "salary": "10 000–13 000 zł brutto / mies.",
    "company": "ZUKEN E3 GMBH sp. z o.o. ODDZIAŁ W POLSCE",
    "location": "Kraków",
    "url": "https://www.pracuj.pl/praca/inzynier-wsparcia-technicznego-zuken-e3-series-m-k-krakow,oferta,1004754545"
  }
];
