#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const DIST = path.join(__dirname, 'dist');

// Files to copy flat into dist/
const FILES = [
  'index.html',
  'common.css',
  'common.js',
  'game.config.js',
  'game.session.js',
  'game.road.js',
  'game.cars.js',
  'game.ui.js',
  'game.input.js',
  'game.js',
  'stats.js',
];

const IMAGE_FILES = [
  'images/background.js',
  'images/sprites.js',
  'images/mute.png',
];

const IMAGE_DIRS = [
  'images/sprites',
  'images/background',
];

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function copyFile(src, dest) {
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
  console.log(`  copied: ${path.relative(__dirname, dest)}`);
}

function copyDir(srcDir, destDir) {
  ensureDir(destDir);
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    const src = path.join(srcDir, entry.name);
    const dest = path.join(destDir, entry.name);
    if (entry.isDirectory()) copyDir(src, dest);
    else copyFile(src, dest);
  }
}

// 1. Clean dist
if (fs.existsSync(DIST)) fs.rmSync(DIST, { recursive: true });
ensureDir(DIST);

// 2. Generate jobs.js from jobs.json
const jobsJson = JSON.parse(fs.readFileSync(path.join(__dirname, 'jobs.json'), 'utf8'));
const jobsJs = `var jobs = ${JSON.stringify(jobsJson.listings ?? jobsJson, null, 2)};\n`;
fs.writeFileSync(path.join(DIST, 'jobs.js'), jobsJs);
console.log('  generated: jobs.js');

// 2b. Generate city-list.js from scraper.config.js + presence of cities/<slug>/latest.js
const CFG = require('./scraper/scraper.config.js');
const CITIES_DIR = path.join(__dirname, 'cities');
const availableCities = Object.values(CFG.searches)
  .filter(p => p.enabled !== false)
  .map(p => ({
    slug:  p.outputSlug || p.label.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    label: p.label.replace(/ – .*$/, '').trim(),  // strip " – all" suffix
  }))
  .filter(c => fs.existsSync(path.join(CITIES_DIR, c.slug, 'latest.js')));
const cityListJs = `// Auto-generated by build.js — do not edit manually.\nwindow._CITIES = ${JSON.stringify(availableCities, null, 2)};\n`;
fs.writeFileSync(path.join(DIST, 'city-list.js'), cityListJs);
console.log(`  generated: city-list.js  (${availableCities.length} cities: ${availableCities.map(c => c.slug).join(', ')})`);

// 3. Copy static files
for (const file of [...FILES, ...IMAGE_FILES]) {
  copyFile(path.join(__dirname, file), path.join(DIST, file));
}

// 4. Copy image directories
for (const dir of IMAGE_DIRS) {
  copyDir(path.join(__dirname, dir), path.join(DIST, dir));
}

// 5. Build dist/pl/ — full copy of dist/ with a patched index.html
const PL_DIST = path.join(DIST, 'pl');
ensureDir(PL_DIST);

// 5a. Copy every file from dist/ into dist/pl/ (except the pl/ subdir itself)
function mirrorDist(srcDir, destDir) {
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    if (entry.name === 'pl') continue; // don't recurse into the dir we're building
    const src  = path.join(srcDir, entry.name);
    const dest = path.join(destDir, entry.name);
    if (entry.isDirectory()) {
      ensureDir(dest);
      mirrorDist(src, dest);
    } else {
      fs.copyFileSync(src, dest);
    }
  }
}
mirrorDist(DIST, PL_DIST);
console.log('  mirrored dist/ → dist/pl/');

// 5b. Overwrite dist/pl/index.html with the Polish version from pl/index.html
const PL_SRC = path.join(__dirname, 'pl', 'index.html');
if (fs.existsSync(PL_SRC)) {
  // The pl/index.html uses ../ prefixes — strip them since assets now sit alongside it
  let plHtml = fs.readFileSync(PL_SRC, 'utf8');
  plHtml = plHtml.replace(/(["'])\.\.\//g, '$1');
  fs.writeFileSync(path.join(PL_DIST, 'index.html'), plHtml);
  console.log('  wrote: dist/pl/index.html (Polish, paths fixed)');
}

console.log('\nBuild complete → dist/');
