#!/usr/bin/env node
/**
 * phases/normalize.js  —  Phase 2: normalize only
 * ─────────────────────────────────────────────────
 * Reads the latest raw/<timestamp>.json for each profile,
 * applies all transforms (salary parsing, job level classification, field
 * slimming), and writes:
 *
 *   output/<slug>/latest.json   — slim JSON (consumed by API / future use)
 *   output/<slug>/latest.js     — JS var for direct <script src> use in browser
 *
 * Also writes to cities/<slug>/ for backward compat with the existing UI.
 *
 * Does NOT: launch a browser, touch S3.
 *
 * Usage:
 *   node phases/normalize.js                    # all enabled profiles
 *   node phases/normalize.js --search 03        # one profile
 *   node phases/normalize.js --searches 01,03   # specific profiles
 *   node phases/normalize.js --search 03 --raw path/to/specific.json
 */

"use strict";

const path = require("path");
const fs   = require("fs");

const lib = require("./lib");
lib.loadEnv(path.join(__dirname, ".."));

const CFG      = require("../scraper.config.js");
const args     = process.argv.slice(2);
const profiles = lib.resolveProfiles(CFG, args);

// --raw <file>  overrides the auto-detected latest raw file (only for single profile runs)
const rawOverride = (() => { const i = args.indexOf("--raw"); return i !== -1 && args[i+1] ? args[i+1] : ""; })();

// ── Transform raw listings → slim output ─────────────────────────────────────
function transform(rawListings) {
  return rawListings
    .filter(l => l.title && l.url)
    .map(l => ({
      id:              l.id              || null,
      title:           l.title,
      salary:          l.salary          || null,
      salaryAvg:       lib.parseSalary(l.salary),
      company:         l.company         || null,
      companyId:       l.companyId       || null,
      location:        l.location        || (l.isWholePoland ? "Cała Polska" : null),
      isWholePoland:   l.isWholePoland   ?? false,
      workModes:       l.workModes       || [],
      workSchedules:   l.workSchedules   || [],
      typesOfContract: l.typesOfContract || [],
      positionLevels:  l.positionLevels  || [],
      isRemote:        l.isRemote        ?? false,
      isSuperOffer:    l.isSuperOffer    ?? false,
      isOptionalCv:    l.isOptionalCv    ?? false,
      isOneClickApply: l.isOneClickApply ?? false,
      publishedAt:     l.publishedAt     || null,
      expiresAt:       l.expiresAt       || null,
      description:     l.description     || null,
      url:             l.url,
      jobLevel:        lib.classifyPositionLevel(l.positionLevels),
      categories:      l.categories      || undefined,
    }));
}

// ── Normalize one profile ─────────────────────────────────────────────────────
function normalizeProfile(profile) {
  const slug = profile.outputSlug || lib.toSlug(profile.label || profile.key);

  // Resolve raw file
  const rawFile = rawOverride || lib.latestRawFile(CFG, profile);
  if (!rawFile) {
    console.error(`❌  [${profile.key}] No raw file found. Run phase 1 (scrape) first.`);
    return false;
  }

  console.log(`\n${"─".repeat(60)}`);
  console.log(`🔑  [${profile.key}] ${profile.label}  —  normalizing`);
  console.log(`   raw: ${rawFile}`);
  console.log(`${"─".repeat(60)}\n`);

  const raw         = JSON.parse(fs.readFileSync(rawFile, "utf8"));
  const listings    = transform(raw.listings);
  const normalizedAt = new Date().toISOString();

  const meta = {
    ...raw.meta,
    normalizedAt,
    totalNormalized: listings.length,
  };

  // ── output/<slug>/ ────────────────────────────────────────────────────────
  const outDirPath = lib.outputDir(CFG, profile);
  fs.mkdirSync(outDirPath, { recursive: true });

  const json    = JSON.stringify({ meta, listings }, null, 2);
  const jsVar   = slug.replace(/-/g, "_");  // valid JS identifier
  const jsContent = `// Auto-generated by phases/normalize.js — do not edit manually.\n// Profile: [${profile.key}] ${profile.label}  Normalized: ${normalizedAt}\nvar cityJobs = ${JSON.stringify(listings, null, 2)};\n`;

  const latestJson = path.join(outDirPath, "latest.json");
  const latestJs   = path.join(outDirPath, "latest.js");
  fs.writeFileSync(latestJson, json,      "utf8");
  fs.writeFileSync(latestJs,   jsContent, "utf8");
  console.log(`  ✔  output/${slug}/latest.json  (${listings.length} listings)`);
  console.log(`  ✔  output/${slug}/latest.js`);

  // ── cities/<slug>/  — backward compat with existing UI ────────────────────
  const citiesDir = path.resolve(path.join(__dirname, "../.."), CFG.citiesDir.replace("../", ""));
  const cityDir   = path.join(citiesDir, slug);
  fs.mkdirSync(cityDir, { recursive: true });

  // Timestamped + latest for cities/ as well
  const timestamp    = normalizedAt.replace(/[:.]/g, "-").replace("Z", "z");
  const cityTsJson   = path.join(cityDir, `${timestamp}.json`);
  const cityLatJson  = path.join(cityDir, "latest.json");
  const cityTsJs     = path.join(cityDir, `${timestamp}.js`);
  const cityLatJs    = path.join(cityDir, "latest.js");

  fs.writeFileSync(cityTsJson,  json,      "utf8");
  fs.writeFileSync(cityLatJson, json,      "utf8");
  fs.writeFileSync(cityTsJs,    jsContent, "utf8");
  fs.writeFileSync(cityLatJs,   jsContent, "utf8");
  console.log(`  ✔  cities/${slug}/latest.json  (compat)`);
  console.log(`  ✔  cities/${slug}/latest.js    (compat)`);

  return { slug, listingCount: listings.length, normalizedAt, latestJson, latestJs, cityDir };
}

// ── Entry point ───────────────────────────────────────────────────────────────
(async () => {
  console.log(`\n🔧  Phase 2 — normalize  (${profiles.length} profile(s))\n`);
  let ok = 0, fail = 0;
  for (const profile of profiles) {
    const result = normalizeProfile(profile);
    result ? ok++ : fail++;
  }
  console.log(`\n✅  Normalize phase complete  (${ok} ok, ${fail} failed)\n`);
  if (fail) process.exit(1);
})().catch(err => { console.error("Fatal:", err); process.exit(1); });
