// Auto-generated by scrape_jobs.js — do not edit manually.
// City: Warsaw  Scraped: 2026-04-07T15:11:51.385Z
var cityJobs = [
  {
    "title": "Senior API Management & Governance Architect (k/m/x)",
    "salary": "180–210 zł netto (+ VAT) / godz.",
    "company": "SQUARE ONE RESOURCES sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/senior-api-management-governance-architect-k-m-x-warszawa,oferta,1004710002"
  },
  {
    "title": "Księgowy / Księgowa",
    "salary": "8 000–10 000 zł brutto / mies.",
    "company": "KANCELARIA ROMANIUK sp. z o.o.",
    "location": "Piaseczno",
    "url": "https://www.pracuj.pl/praca/ksiegowy-ksiegowa-piaseczno-generala-zajaczka-9b,oferta,1004754971"
  },
  {
    "title": "Doradca Klienta Indywidualnego",
    "salary": "8 750–20 000 zł / mies. (zal. od umowy)",
    "company": "Tutlo Sp. z o.o.",
    "location": "Warszawa, Śródmieście",
    "url": "https://www.pracuj.pl/praca/doradca-klienta-indywidualnego-warszawa-nowogrodzka-42,oferta,1004742342"
  },
  {
    "title": "Data Engineer - databricks (k/m/x)",
    "salary": "100–140 zł netto (+ VAT) / godz.",
    "company": "SQUARE ONE RESOURCES sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/data-engineer-databricks-k-m-x-warszawa,oferta,1004745269"
  },
  {
    "title": "Automation Tester (SQL, Cypress) k/m/*",
    "salary": "70–110 zł netto (+ VAT) / godz.",
    "company": "SQUARE ONE RESOURCES sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/automation-tester-sql-cypress-k-m-warszawa,oferta,1004745266"
  },
  {
    "title": "Franczyzobiorca w branży e-commerce i logistyki",
    "salary": "20 000–35 000 zł netto (+ VAT) / mies.",
    "company": "Mail Boxes Etc.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/franczyzobiorca-w-branzy-e-commerce-i-logistyki-warszawa,oferta,1004706481"
  },
  {
    "title": "Sprzedawca/Kasjer, Sprzedawczyni/Kasjerka",
    "salary": "1 525–1 550 zł brutto / mies.",
    "company": "KAUFLAND",
    "location": "Wołomin",
    "url": "https://www.pracuj.pl/praca/sprzedawca-kasjer-sprzedawczyni-kasjerka-wolomin-wilenska-49,oferta,1004697889"
  },
  {
    "title": "Sprzedawca/Kasjer, Sprzedawczyni/Kasjerka",
    "salary": "1 525–1 550 zł brutto / mies.",
    "company": "KAUFLAND",
    "location": "Warszawa, Wola",
    "url": "https://www.pracuj.pl/praca/sprzedawca-kasjer-sprzedawczyni-kasjerka-warszawa-polczynska-4,oferta,1004697894"
  },
  {
    "title": "Senior Backend Python Developer",
    "salary": "20 000–25 000 zł / mies. (zal. od umowy)",
    "company": "Fundacja Szkoła w Chmurze",
    "location": "Warszawa, Żoliborz",
    "url": "https://www.pracuj.pl/praca/senior-backend-python-developer-warszawa-powazkowska-44c,oferta,1004700400"
  },
  {
    "title": "Data Governance Specialist",
    "salary": "24 000–27 000 zł netto (+ VAT) / mies.",
    "company": "Mindbox Sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/data-governance-specialist-warszawa,oferta,1004700420"
  },
  {
    "title": "Operator Produkcji / Operatorka Produkcji",
    "salary": "5 600–6 000 zł brutto / mies.",
    "company": "LOTTE Wedel",
    "location": "Warszawa, Praga-Południe",
    "url": "https://www.pracuj.pl/praca/operator-produkcji-operatorka-produkcji-warszawa-jana-zamoyskiego-28-30,oferta,1004706565"
  },
  {
    "title": "Team Leader Zespołu Ambasadorów marki PLOOM w kanale Retail",
    "salary": "6 400–8 200 zł brutto / mies.",
    "company": "Modus",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/team-leader-zespolu-ambasadorow-marki-ploom-w-kanale-retail-warszawa,oferta,1004706537"
  },
  {
    "title": "Project Manager / Managerka",
    "salary": "5 000–12 000 zł / mies. (zal. od umowy)",
    "company": "Fundacja Szkoła w Chmurze",
    "location": "Warszawa, Żoliborz",
    "url": "https://www.pracuj.pl/praca/project-manager-managerka-warszawa-powazkowska-44c,oferta,1004715992"
  },
  {
    "title": "Automatyczka / Automatyk w Oddziale Utrzymania Ruchu",
    "salary": "6 400–8 500 zł brutto / mies.",
    "company": "Miejskie Przedsiębiorstwo Wodociągów i Kanalizacji w m. st. Warszawie Spółka Akcyjna",
    "location": "Warszawa, Ochota",
    "url": "https://www.pracuj.pl/praca/automatyczka-automatyk-w-oddziale-utrzymania-ruchu-warszawa-koszykowa-81,oferta,1004715987"
  },
  {
    "title": "DevOps Engineer (f/m)",
    "salary": "140–160 zł netto (+ VAT) / godz.",
    "company": "KMD Poland Sp. z o.o.",
    "location": "Warszawa, Śródmieście",
    "url": "https://www.pracuj.pl/praca/devops-engineer-f-m-warszawa-inflancka-4a,oferta,1004716000"
  },
  {
    "title": "Junior Java Developer (f/m)",
    "salary": "7 000–10 000 zł / mies. (zal. od umowy)",
    "company": "Netcompany Poland sp. z o.o.",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/junior-java-developer-f-m-warszawa-pulawska-180,oferta,1004718574"
  },
  {
    "title": "Java Developer (f/m)",
    "salary": "8 000–12 000 zł / mies. (zal. od umowy)",
    "company": "Netcompany Poland sp. z o.o.",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/java-developer-f-m-warszawa-pulawska-180,oferta,1004718570"
  },
  {
    "title": "Junior .Net Developer (f/m)",
    "salary": "7 000–10 000 zł / mies. (zal. od umowy)",
    "company": "Netcompany Poland sp. z o.o.",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/junior-net-developer-f-m-warszawa-pulawska-180,oferta,1004718576"
  },
  {
    "title": ".Net Developer (f/m)",
    "salary": "8 000–12 000 zł / mies. (zal. od umowy)",
    "company": "Netcompany Poland sp. z o.o.",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/net-developer-f-m-warszawa-pulawska-180,oferta,1004718527"
  },
  {
    "title": "Salesforce Developer",
    "salary": "140–180 zł netto (+ VAT) / godz.",
    "company": "Cyclad",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/salesforce-developer-warszawa,oferta,1004718579"
  },
  {
    "title": "Graficzka/Grafik DTP (flexo i cyfra)",
    "salary": "6 500–8 500 zł / mies. (zal. od umowy)",
    "company": "LabelStore industrial solutions",
    "location": "Warszawa, Bielany",
    "url": "https://www.pracuj.pl/praca/graficzka-grafik-dtp-flexo-i-cyfra-warszawa-palisadowa-20-22,oferta,1004716030"
  },
  {
    "title": "Stacjonarny Przedstawiciel Handlowy / Stacjonarna Przedstawicielka Handlowa",
    "salary": "6 900–10 000 zł brutto / mies.",
    "company": "ANTAR MEDICAL SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",
    "location": "Warszawa, Targówek",
    "url": "https://www.pracuj.pl/praca/stacjonarny-przedstawiciel-handlowy-stacjonarna-przedstawicielka-handlowa-warszawa-labiszynska-21c,oferta,1004718623"
  },
  {
    "title": "Mechaniczka- Konserwatorka /Mechanik – Konserwator w Oddziale Eksploatacji Przepompowni (k/m/n)",
    "salary": "5 600–7 300 zł brutto / mies.",
    "company": "Miejskie Przedsiębiorstwo Wodociągów i Kanalizacji w m. st. Warszawie Spółka Akcyjna",
    "location": "Warszawa, Praga-Północ",
    "url": "https://www.pracuj.pl/praca/mechaniczka-konserwatorka-mechanik-konserwator-w-oddziale-eksploatacji-przepompo-warszawa-jagiellonska-65-67,oferta,1004725116"
  },
  {
    "title": "Data Engineer (Spark / Streaming / Java)",
    "salary": "160–200 zł netto (+ VAT) / godz.",
    "company": "KMD Poland Sp. z o.o.",
    "location": "Warszawa, Śródmieście",
    "url": "https://www.pracuj.pl/praca/data-engineer-spark-streaming-java-warszawa-inflancka-4a,oferta,1004725118"
  },
  {
    "title": "National Account Manager (NAM)",
    "salary": "8 500–10 000 zł / mies. (zal. od umowy)",
    "company": "WeNet Group SA",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/national-account-manager-nam-warszawa-postepu-14,oferta,1004725164"
  },
  {
    "title": "Konsultant / Konsultantka Sprzedaży Bezpośredniej",
    "salary": "5 000–6 500 zł brutto / mies.",
    "company": "WeNet Group SA",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/konsultant-konsultantka-sprzedazy-bezposredniej-warszawa-postepu-14,oferta,1004725165"
  },
  {
    "title": "Starszy Specjalista / Starsza Specjalistka ds. Sprzedaży Usług Marketingowych",
    "salary": "5 500–6 500 zł brutto / mies.",
    "company": "WeNet sp. z o.o.",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/starszy-specjalista-starsza-specjalistka-ds-sprzedazy-uslug-marketingowych-warszawa-postepu-14,oferta,1004725135"
  },
  {
    "title": "Młodszy Specjalista / Młodsza Specjalistka ds. Sprzedaży Usług Marketingowych",
    "salary": "4 900–5 400 zł brutto / mies.",
    "company": "WeNet sp. z o.o.",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/mlodszy-specjalista-mlodsza-specjalistka-ds-sprzedazy-uslug-marketingowych-warszawa-postepu-14,oferta,1004725145"
  },
  {
    "title": "Ekspert / Ekspertka ds. Sprzedaży SEO & ADS",
    "salary": "6 000–8 000 zł / mies. (zal. od umowy)",
    "company": "WeNet sp. z o.o.",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/ekspert-ekspertka-ds-sprzedazy-seo-ads-warszawa-postepu-14,oferta,1004725129"
  },
  {
    "title": "Opiekun / Opiekunka Klienta - mKiosk mBanku",
    "salary": "5 750–10 150 zł brutto / mies.",
    "company": "mFinanse S.A.",
    "location": "Janki (pow. pruszkowski)",
    "url": "https://www.pracuj.pl/praca/opiekun-opiekunka-klienta-mkiosk-mbanku-janki-pow-pruszkowski,oferta,1004736650"
  },
  {
    "title": "Opiekun / Opiekunka Klienta - mKiosk mBanku",
    "salary": "5 750–10 150 zł brutto / mies.",
    "company": "mFinanse S.A.",
    "location": "Marki",
    "url": "https://www.pracuj.pl/praca/opiekun-opiekunka-klienta-mkiosk-mbanku-marki,oferta,1004736639"
  },
  {
    "title": "Opiekun / Opiekunka Klienta - mKiosk mBanku",
    "salary": "5 750–10 150 zł brutto / mies.",
    "company": "mFinanse S.A.",
    "location": "Piaseczno",
    "url": "https://www.pracuj.pl/praca/opiekun-opiekunka-klienta-mkiosk-mbanku-piaseczno,oferta,1004736572"
  },
  {
    "title": "Opiekun / Opiekunka Klienta - mKiosk mBanku",
    "salary": "5 750–10 150 zł brutto / mies.",
    "company": "mFinanse S.A.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/opiekun-opiekunka-klienta-mkiosk-mbanku-warszawa,oferta,1004736643"
  },
  {
    "title": "Opiekun / Opiekunka Klienta - mKiosk mBanku",
    "salary": "5 750–10 150 zł brutto / mies.",
    "company": "mFinanse S.A.",
    "location": "Wołomin",
    "url": "https://www.pracuj.pl/praca/opiekun-opiekunka-klienta-mkiosk-mbanku-wolomin,oferta,1004736647"
  },
  {
    "title": "Młodszy specjalista ds. administracji (M/K)",
    "salary": "33–6 000 zł / mies. (zal. od umowy)",
    "company": "Devire",
    "location": "Wolica (pow. pruszkowski)",
    "url": "https://www.pracuj.pl/praca/mlodszy-specjalista-ds-administracji-m-k-wolica-pow-pruszkowski,oferta,1004754795"
  },
  {
    "title": "Lektor / Lektorka - Nauczyciel / Nauczycielka języka angielskiego (ONLINE)",
    "salary": "5 400–7 000 zł / mies. (zal. od umowy)",
    "company": "Tutlo Sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/lektor-lektorka-nauczyciel-nauczycielka-jezyka-angielskiego-online-warszawa,oferta,1004748769"
  },
  {
    "title": "SAP IS-U Billing Analyst",
    "salary": "25 200–29 400 zł netto (+ VAT) / mies.",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/sap-is-u-billing-analyst-warszawa,oferta,1004751491"
  },
  {
    "title": "Senior Fullstack Engineer",
    "salary": "26 500–30 000 zł brutto / mies.",
    "company": "Motife Sp. z o.o.",
    "location": "Warszawa, Wola",
    "url": "https://www.pracuj.pl/praca/senior-fullstack-engineer-warszawa-grzybowska-60,oferta,1004736198"
  },
  {
    "title": "Analityk Biznesowy",
    "salary": "14 000–17 000 zł netto (+ VAT) / mies.",
    "company": "Develocraft sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/analityk-biznesowy-warszawa,oferta,1004742326"
  },
  {
    "title": "Młodszy Specjalista / Młodsza Specjalistka ds. Komunikacji i Treści (sektor medyczny)",
    "salary": "5 000–7 000 zł brutto / mies.",
    "company": "OGÓLNOPOLSKA IZBA GOSPODARCZA WYROBÓW MEDYCZNYCH \"POLMED\"",
    "location": "Warszawa, Śródmieście",
    "url": "https://www.pracuj.pl/praca/mlodszy-specjalista-mlodsza-specjalistka-ds-komunikacji-i-tresci-sektor-medyczny-warszawa-tytusa-chalubinskiego-8,oferta,1004724922"
  },
  {
    "title": "Doradca techniczno-handlowy (k/m)",
    "salary": "10 000–15 000 zł brutto / mies.",
    "company": "Randstad Polska Sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/doradca-techniczno-handlowy-k-m-warszawa,oferta,1004748341"
  },
  {
    "title": "Cybersecurity Design Reviewer - Architect",
    "salary": "24 000–31 000 zł netto (+ VAT) / mies.",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/cybersecurity-design-reviewer-architect-warszawa,oferta,1004736184"
  },
  {
    "title": "Technik serwisant (K/M)",
    "salary": "5 500–6 000 zł brutto / mies.",
    "company": "Devire",
    "location": "Piaseczno",
    "url": "https://www.pracuj.pl/praca/technik-serwisant-k-m-piaseczno,oferta,1004727913"
  },
  {
    "title": "TV Planner / Buyer",
    "salary": "5 166–9 166 zł brutto / mies.",
    "company": "WPP Media",
    "location": "Warszawa, Praga-Północ",
    "url": "https://www.pracuj.pl/praca/tv-planner-buyer-warszawa-plac-konesera-11,oferta,1004748319"
  },
  {
    "title": "Młodszy Specjalista ds. należności (M/K)",
    "salary": "33–36 zł brutto / godz.",
    "company": "Devire",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/mlodszy-specjalista-ds-naleznosci-m-k-warszawa,oferta,1004727912"
  },
  {
    "title": "Senior Java Developer - ASAP",
    "salary": "18 900–24 150 zł / mies. (zal. od umowy)",
    "company": "ITDS Polska Sp. z o.o.",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/senior-java-developer-asap-warszawa,oferta,1004724857"
  },
  {
    "title": "Oracle Integration Specialist (AIA/SOA/OSB)",
    "salary": "16 000–22 000 zł netto (+ VAT) / mies.",
    "company": "Cyclad",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/oracle-integration-specialist-aia-soa-osb-warszawa,oferta,1004736166"
  },
  {
    "title": "Asystent / Asystentka Działu Produktu i Zakupów (Home&Garden)",
    "salary": "6 000–8 000 zł brutto / mies.",
    "company": "Meblobranie.pl Sp. z o.o.",
    "location": "Warszawa, Wola",
    "url": "https://www.pracuj.pl/praca/asystent-asystentka-dzialu-produktu-i-zakupow-home-garden-warszawa-gizow-6,oferta,1004754895"
  },
  {
    "title": "Młodszy inżynier / Młodsza inżynierka projektu",
    "salary": "5 500–8 000 zł brutto / mies.",
    "company": "MP PROCESS sp. z o.o.",
    "location": "Słomin (pow. pruszkowski)",
    "url": "https://www.pracuj.pl/praca/mlodszy-inzynier-mlodsza-inzynierka-projektu-slomin-pow-pruszkowski,oferta,1004754892"
  },
  {
    "title": "Główna/y Księgowa/y (profil z biura rach. + znajomość SAP)",
    "salary": "18 000–22 000 zł brutto / mies.",
    "company": "Michael Page",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/glowna-y-ksiegowa-y-profil-z-biura-rach-%2b-znajomosc-sap-warszawa,oferta,1004742277"
  },
  {
    "title": "Pracownik / Pracowniczka Restauracji KFC Suchy Las Ibis",
    "salary": "31–32 zł brutto / godz.",
    "company": "AmRest Sp. z o.o. - KFC",
    "location": "Suchy Las (pow. pruszkowski)",
    "url": "https://www.pracuj.pl/praca/pracownik-pracowniczka-restauracji-kfc-suchy-las-ibis-suchy-las-pow-pruszkowski,oferta,1004754880"
  },
  {
    "title": "Key Account Manager (izolacje techniczne)",
    "salary": "15 000 zł brutto / mies.",
    "company": "SALES HR",
    "location": "Warszawa",
    "url": "https://www.pracuj.pl/praca/key-account-manager-izolacje-techniczne-warszawa,oferta,1004754874"
  },
  {
    "title": "Specjalista ds. Planowania (K/M)",
    "salary": "6 510–8 505 zł brutto / mies.",
    "company": "Airbus Poland S.A.",
    "location": "Warszawa, Włochy",
    "url": "https://www.pracuj.pl/praca/specjalista-ds-planowania-k-m-warszawa-aleja-krakowska-110-114,oferta,1004706191"
  },
  {
    "title": "Senior QA Engineer - Ecommerce / OMS / WMS / PIM",
    "salary": "80–120 zł netto (+ VAT) / godz.",
    "company": "FORTEGIA SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",
    "location": "Warszawa, Mokotów",
    "url": "https://www.pracuj.pl/praca/senior-qa-engineer-ecommerce-oms-wms-pim-warszawa-gotarda-9,oferta,1004754828"
  }
];
